# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-24 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='language',
            field=models.CharField(choices=[('EN', 'English'), ('DE', 'Deutsch')], default='EN', max_length=20),
        ),
    ]
