# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-03 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='img/%Y/%m/%d'),
        ),
    ]
